spring:
  application:
    name: EurekaServer

---
spring:
  profiles: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

  instance:
    prefer-ip-address: true
server:
  port: 1000
---
spring:
  profiles: peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

  instance:
    prefer-ip-address: true
server:
  port: 1001
