spring:
  application:
    name: EurekaServer

eureka.server.use-read-only-response-cache: false
eureka.server.eviction-interval-timer-in-ms: 3000

---
spring:
  profiles: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

  instance:
    prefer-ip-address: true
server:
  port: 1000
---
spring:
  profiles: peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

  instance:
    prefer-ip-address: true
server:
  port: 1001


